export const states = [
  'Andaman and Nicobar Islands',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chandigarh',
  'Chhattisgarh',
  'Dadra and Nagar Haveli Daman and Diu',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Ladakh',
  'Lakshadweep',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Puducherry',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
];
export const statesWithShortCode = [
  {name: 'Andhra Pradesh', short_code: 'AP'},
  {name: 'Arunachal Pradesh', short_code: 'AR'},
  {name: 'Assam', short_code: 'AS'},
  {name: 'Bihar', short_code: 'BR'},
  {name: 'Chhattisgarh', short_code: 'CG'},
  {name: 'Goa', short_code: 'GA'},
  {name: 'Gujarat', short_code: 'GJ'},
  {name: 'Haryana', short_code: 'HR'},
  {name: 'Himachal Pradesh', short_code: 'HP'},
  {name: 'Jammu and Kashmir', short_code: 'JK'},
  {name: 'Jharkhand', short_code: 'JH'},
  {name: 'Karnataka', short_code: 'KA'},
  {name: 'Kerala', short_code: 'KL'},
  {name: 'Madhya Pradesh', short_code: 'MP'},
  {name: 'Maharashtra', short_code: 'MH'},
  {name: 'Manipur', short_code: 'MN'},
  {name: 'Meghalaya', short_code: 'ML'},
  {name: 'Mizoram', short_code: 'MZ'},
  {name: 'Nagaland', short_code: 'NL'},
  {name: 'Odisha', short_code: 'OD'},
  {name: 'Punjab', short_code: 'PB'},
  {name: 'Rajasthan', short_code: 'RJ'},
  {name: 'Sikkim', short_code: 'SK'},
  {name: 'Tamil Nadu', short_code: 'TN'},
  {name: 'Telangana', short_code: 'TG'},
  {name: 'Tripura', short_code: 'TR'},
  {name: 'Uttarakhand', short_code: 'UK'},
  {name: 'Uttar Pradesh', short_code: 'UP'},
  {name: 'West Bengal', short_code: 'WB'},
  {name: 'Andaman and Nicobar Islands', short_code: 'AN'},
  {name: 'Chandigarh', short_code: 'CH'},
  {name: 'Dadra and Nagar Haveli', short_code: 'DN'},
  {name: 'Daman and Diu', short_code: 'DD'},
  {name: 'Delhi', short_code: 'DL'},
  {name: 'Lakshadweep', short_code: 'LD'},
  {name: 'Puducherry', short_code: 'PY'},
  {name: 'Ladakh', short_code: 'LK'},
];
