const IMAGE_URL = {
  logo: require('@/assets/images/logo_white.png'),
  filter: require('@/assets/images/filter_new.png'),
  privacy: require('@/assets/images/privacy.png'),
  terms: require('@/assets/images/terms.png'),
  trucklogo: require('@/assets/images/trucklogo.png'),
  edit: require('@/assets/images/edit.png'),
  logistics: require('@/assets/images/logistics.png'),
  agWallet: require('@/assets/images/ag_wallet.png'),
  pgIcon: require('@/assets/images/pg_icon.png'),
  copy: require('@/assets/images/copy.png'),
  filterWhite: require('@/assets/images/filter_white.png'),
  nodata: require('@/assets/images/nodata.png'),
  truckIcon: require('@/assets/images/truckIcon.png'),
  profileLogo: require('@/assets/images/profile_logo.png'),
  loadActive: require('@/assets/images/active.png'),
  loadActiveBlack: require('@/assets/images/activeblack.png'),
  filterCarrier: require('@/assets/images/filter.png'),
  rupeeIcon: require('@/assets/images/rupeeIcon.png'),
  sidedArrow: require('@/assets/images/2sidedArrow.png'),
  bg: require('@/assets/images/bg1.png'),
  truck: require('@/assets/images/truck_new.png'),
  truck_bg: require('@/assets/images/truck-bg.png'),
  notification: require('@/assets/images/notification.png'),
  refer: require('@/assets/images/refer.png'),
  googleplay: require('@/assets/images/googleplay.png'),
  avatar: require('@/assets/images/Avatar.png'),
};
export default IMAGE_URL;
